export const CATEGORIAS_RECEITAS = [
  "americana",
  "bebida",
  "brasileira",
  "cafe-manha",
  "carne",
  "doce",
  "europeia",
  "guarnicao",
  "japonesa",
  "lanche",
  "latina",
  "low-carb",
  "massa",
  "molhos-pastas",
  "petisco",
  "receita-rapida",
  "salada",
  "salgado",
  "semanal",
  "sem-gluten",
  "sobremesa",
  "sopa",
].sort((a, b) => a.localeCompare(b, "pt-BR"));